# https://docs.github.com/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@angular-eslint/*'
          - angular-eslint
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
