/**
 * Nomes das habilidades em pt-BR, por slug da PokéAPI (que não tem esses
 * nomes em português). Tradução própria: segue os nomes oficiais dos jogos
 * quando conhecidos. Habilidade sem entrada aqui cai para o slug formatado.
 */
export const ABILITY_LABELS: Record<string, string> = {
  stench: 'Fedor',
  drizzle: 'Garoa',
  'speed-boost': 'Aceleração',
  'battle-armor': 'Armadura de Batalha',
  sturdy: 'Robustez',
  damp: 'Umidade',
  limber: 'Flexibilidade',
  'sand-veil': 'Véu de Areia',
  static: 'Estática',
  'volt-absorb': 'Absorção Elétrica',
  'water-absorb': 'Absorção de Água',
  oblivious: 'Distraído',
  'cloud-nine': 'Céu Limpo',
  'compound-eyes': 'Olhos Compostos',
  insomnia: 'Insônia',
  'color-change': 'Mudança de Cor',
  immunity: 'Imunidade',
  'flash-fire': 'Absorção de Fogo',
  'shield-dust': 'Pó Protetor',
  'own-tempo': 'Ritmo Próprio',
  'suction-cups': 'Ventosas',
  intimidate: 'Intimidação',
  'shadow-tag': 'Prisão das Sombras',
  'rough-skin': 'Pele Áspera',
  'wonder-guard': 'Guarda Maravilha',
  levitate: 'Levitação',
  'effect-spore': 'Esporos',
  synchronize: 'Sincronia',
  'clear-body': 'Corpo Puro',
  'natural-cure': 'Cura Natural',
  'lightning-rod': 'Para-raios',
  'serene-grace': 'Graça Serena',
  'swift-swim': 'Nado Veloz',
  chlorophyll: 'Clorofila',
  illuminate: 'Iluminação',
  trace: 'Rastreio',
  'huge-power': 'Força Imensa',
  'poison-point': 'Ponta Venenosa',
  'inner-focus': 'Foco Interior',
  'magma-armor': 'Armadura de Magma',
  'water-veil': 'Véu de Água',
  'magnet-pull': 'Ímã',
  soundproof: 'À Prova de Som',
  'rain-dish': 'Prato de Chuva',
  'sand-stream': 'Tempestade de Areia',
  pressure: 'Pressão',
  'thick-fat': 'Gordura Espessa',
  'early-bird': 'Madrugador',
  'flame-body': 'Corpo em Chamas',
  'run-away': 'Fuga',
  'keen-eye': 'Olhar Aguçado',
  'hyper-cutter': 'Pinças Fortes',
  pickup: 'Coletor',
  truant: 'Preguiça',
  hustle: 'Afobação',
  'cute-charm': 'Charme',
  plus: 'Positivo',
  minus: 'Negativo',
  forecast: 'Previsão do Tempo',
  'sticky-hold': 'Aderência',
  'shed-skin': 'Troca de Pele',
  guts: 'Garra',
  'marvel-scale': 'Escama Maravilhosa',
  'liquid-ooze': 'Lodo Líquido',
  overgrow: 'Supercrescimento',
  blaze: 'Chama',
  torrent: 'Torrente',
  swarm: 'Enxame',
  'rock-head': 'Cabeça de Pedra',
  drought: 'Seca',
  'arena-trap': 'Armadilha de Arena',
  'vital-spirit': 'Espírito Vital',
  'white-smoke': 'Fumaça Branca',
  'pure-power': 'Força Pura',
  'shell-armor': 'Armadura de Concha',
  'air-lock': 'Bloqueio Aéreo',
  'tangled-feet': 'Pés Trançados',
  'motor-drive': 'Motor Elétrico',
  rivalry: 'Rivalidade',
  steadfast: 'Firmeza',
  'snow-cloak': 'Manto de Neve',
  gluttony: 'Gula',
  'anger-point': 'Ponto de Fúria',
  unburden: 'Desapego',
  heatproof: 'À Prova de Calor',
  simple: 'Simples',
  'dry-skin': 'Pele Seca',
  download: 'Download',
  'iron-fist': 'Punho de Ferro',
  'poison-heal': 'Cura Venenosa',
  adaptability: 'Adaptabilidade',
  'skill-link': 'Golpes Encadeados',
  hydration: 'Hidratação',
  'solar-power': 'Energia Solar',
  'quick-feet': 'Pés Ligeiros',
  normalize: 'Normalizar',
  sniper: 'Atirador de Elite',
  'magic-guard': 'Guarda Mágica',
  'no-guard': 'Sem Guarda',
  stall: 'Lentidão',
  technician: 'Técnico',
  'leaf-guard': 'Guarda de Folhas',
  klutz: 'Desastrado',
  'mold-breaker': 'Quebra-Molde',
  'super-luck': 'Supersorte',
  aftermath: 'Explosão Final',
  anticipation: 'Antecipação',
  forewarn: 'Pressentimento',
  unaware: 'Indiferença',
  'tinted-lens': 'Lente Colorida',
  filter: 'Filtro',
  'slow-start': 'Partida Lenta',
  scrappy: 'Brigão',
  'storm-drain': 'Ralo',
  'ice-body': 'Corpo de Gelo',
  'solid-rock': 'Rocha Sólida',
  'snow-warning': 'Alerta de Neve',
  'honey-gather': 'Coleta de Mel',
  frisk: 'Revista',
  reckless: 'Imprudente',
  multitype: 'Multitipo',
  'flower-gift': 'Presente Floral',
  'bad-dreams': 'Pesadelos',
  pickpocket: 'Batedor de Carteira',
  'sheer-force': 'Força Bruta',
  contrary: 'Do Contra',
  unnerve: 'Nervosismo',
  defiant: 'Desafiador',
  defeatist: 'Derrotista',
  'cursed-body': 'Corpo Amaldiçoado',
  healer: 'Curandeiro',
  'friend-guard': 'Proteção Amiga',
  'weak-armor': 'Armadura Frágil',
  'heavy-metal': 'Metal Pesado',
  'light-metal': 'Metal Leve',
  multiscale: 'Multiescamas',
  'toxic-boost': 'Impulso Tóxico',
  'flare-boost': 'Impulso Flamejante',
  harvest: 'Colheita',
  telepathy: 'Telepatia',
  moody: 'Temperamental',
  overcoat: 'Sobretudo',
  'poison-touch': 'Toque Venenoso',
  regenerator: 'Regenerador',
  'big-pecks': 'Peito Estufado',
  'sand-rush': 'Corrida na Areia',
  'wonder-skin': 'Pele Maravilha',
  analytic: 'Analítico',
  illusion: 'Ilusão',
  imposter: 'Impostor',
  infiltrator: 'Infiltrador',
  mummy: 'Múmia',
  moxie: 'Ousadia',
  justified: 'Justiceiro',
  rattled: 'Assustado',
  'magic-bounce': 'Reflexo Mágico',
  'sap-sipper': 'Comedor de Seiva',
  prankster: 'Travesso',
  'sand-force': 'Força da Areia',
  'iron-barbs': 'Farpas de Ferro',
  'zen-mode': 'Modo Zen',
  'victory-star': 'Estrela da Vitória',
  turboblaze: 'Turbochama',
  teravolt: 'Teravolt',
  'aroma-veil': 'Véu de Aroma',
  'flower-veil': 'Véu Floral',
  'cheek-pouch': 'Bochechas Cheias',
  protean: 'Proteano',
  'fur-coat': 'Casaco de Pele',
  magician: 'Mágico',
  bulletproof: 'À Prova de Balas',
  competitive: 'Competitivo',
  'strong-jaw': 'Mandíbula Forte',
  refrigerate: 'Refrigerar',
  'sweet-veil': 'Véu Doce',
  'stance-change': 'Mudança de Postura',
  'gale-wings': 'Asas de Vendaval',
  'mega-launcher': 'Megalançador',
  'grass-pelt': 'Pelagem de Grama',
  symbiosis: 'Simbiose',
  'tough-claws': 'Garras Duras',
  pixilate: 'Fadificar',
  gooey: 'Gosmento',
  aerilate: 'Aerificar',
  'parental-bond': 'Laço Materno',
  'dark-aura': 'Aura Sombria',
  'fairy-aura': 'Aura Feérica',
  'aura-break': 'Quebra de Aura',
  'primordial-sea': 'Mar Primordial',
  'desolate-land': 'Terra Desolada',
  'delta-stream': 'Corrente Delta',
  stamina: 'Resistência',
  'wimp-out': 'Covardia',
  'emergency-exit': 'Saída de Emergência',
  'water-compaction': 'Compactação de Água',
  merciless: 'Impiedoso',
  'shields-down': 'Escudos Abaixados',
  stakeout: 'Tocaia',
  'water-bubble': "Bolha d'Água",
  steelworker: 'Metalúrgico',
  berserk: 'Fúria',
  'slush-rush': 'Corrida na Neve',
  'long-reach': 'Longo Alcance',
  'liquid-voice': 'Voz Líquida',
  triage: 'Triagem',
  galvanize: 'Galvanizar',
  'surge-surfer': 'Surfista Elétrico',
  schooling: 'Cardume',
  disguise: 'Disfarce',
  'battle-bond': 'Laço de Batalha',
  'power-construct': 'Construção de Poder',
  corrosion: 'Corrosão',
  comatose: 'Comatoso',
  'queenly-majesty': 'Majestade Real',
  'innards-out': 'Vísceras para Fora',
  dancer: 'Dançarino',
  battery: 'Bateria',
  fluffy: 'Fofura',
  dazzling: 'Deslumbrante',
  'soul-heart': 'Coração de Alma',
  'tangling-hair': 'Cabelo Embaraçado',
  receiver: 'Receptor',
  'power-of-alchemy': 'Poder da Alquimia',
  'beast-boost': 'Impulso da Besta',
  'rks-system': 'Sistema RKS',
  'electric-surge': 'Onda Elétrica',
  'psychic-surge': 'Onda Psíquica',
  'misty-surge': 'Onda de Névoa',
  'grassy-surge': 'Onda de Grama',
  'full-metal-body': 'Corpo de Metal Total',
  'shadow-shield': 'Escudo Sombrio',
  'prism-armor': 'Armadura Prismática',
  neuroforce: 'Neuroforça',
  'intrepid-sword': 'Espada Intrépida',
  'dauntless-shield': 'Escudo Inabalável',
  libero: 'Líbero',
  'ball-fetch': 'Busca-Bola',
  'cotton-down': 'Algodão Fofo',
  'propeller-tail': 'Cauda de Hélice',
  'mirror-armor': 'Armadura Espelhada',
  'gulp-missile': 'Míssil Engolido',
  stalwart: 'Inabalável',
  'steam-engine': 'Motor a Vapor',
  'punk-rock': 'Punk Rock',
  'sand-spit': 'Cuspe de Areia',
  'ice-scales': 'Escamas de Gelo',
  ripen: 'Amadurecer',
  'ice-face': 'Rosto de Gelo',
  'power-spot': 'Ponto de Poder',
  mimicry: 'Mimetismo',
  'screen-cleaner': 'Limpa-Telas',
  'steely-spirit': 'Espírito de Aço',
  'perish-body': 'Corpo Perecível',
  'wandering-spirit': 'Espírito Errante',
  'gorilla-tactics': 'Tática de Gorila',
  'neutralizing-gas': 'Gás Neutralizante',
  'pastel-veil': 'Véu Pastel',
  'hunger-switch': 'Troca de Fome',
  'quick-draw': 'Saque Rápido',
  'unseen-fist': 'Punho Invisível',
  'curious-medicine': 'Remédio Curioso',
  transistor: 'Transistor',
  'dragons-maw': 'Bocarra de Dragão',
  'chilling-neigh': 'Relincho Gélido',
  'grim-neigh': 'Relincho Sombrio',
  'as-one-glastrier': 'Unidade (Glastrier)',
  'as-one-spectrier': 'Unidade (Spectrier)',
  'lingering-aroma': 'Aroma Persistente',
  'seed-sower': 'Semeador',
  'thermal-exchange': 'Troca Térmica',
  'anger-shell': 'Casco da Fúria',
  'purifying-salt': 'Sal Purificador',
  'well-baked-body': 'Corpo Bem Assado',
  'wind-rider': 'Cavaleiro do Vento',
  'guard-dog': 'Cão de Guarda',
  'rocky-payload': 'Carga Rochosa',
  'wind-power': 'Energia Eólica',
  'zero-to-hero': 'De Zero a Herói',
  commander: 'Comandante',
  electromorphosis: 'Eletromorfose',
  protosynthesis: 'Protossíntese',
  'quark-drive': 'Propulsão de Quarks',
  'good-as-gold': 'Ouro Puro',
  'vessel-of-ruin': 'Vaso da Ruína',
  'sword-of-ruin': 'Espada da Ruína',
  'tablets-of-ruin': 'Tábuas da Ruína',
  'beads-of-ruin': 'Contas da Ruína',
  'orichalcum-pulse': 'Pulso de Oricalco',
  'hadron-engine': 'Motor de Hádrons',
  opportunist: 'Oportunista',
  'cud-chew': 'Ruminação',
  sharpness: 'Afiado',
  'supreme-overlord': 'Soberano Supremo',
  costar: 'Coadjuvante',
  'toxic-debris': 'Detritos Tóxicos',
  'armor-tail': 'Cauda Blindada',
  'earth-eater': 'Comedor de Terra',
  'mycelium-might': 'Força do Micélio',
  'minds-eye': 'Olho da Mente',
  'supersweet-syrup': 'Xarope Superdoce',
  hospitality: 'Hospitalidade',
  'toxic-chain': 'Corrente Tóxica',
  'embody-aspect': 'Encarnar Aspecto',
  'tera-shift': 'Teramudança',
  'tera-shell': 'Teracasco',
  'teraform-zero': 'Teraformação Zero',
  'poison-puppeteer': 'Titereiro Venenoso',
  'piercing-drill': 'Broca Perfurante',
  dragonize: 'Dragonizar',
  'mega-sol': 'Megassol',
  'spicy-spray': 'Spray Picante',
  eelevate: 'Enguilevação',
  'fire-mane': 'Juba de Fogo',
  'aura-guard': 'Guarda de Aura',
};
